### ISSUE TITLE
Bad "Content-Length" header

### ISSUE THREAD

**Issue by egorsmkv** [nemasu/asmttpd#17]
```
~ > curl --head http://my_host/
HTTP/1.1 200 OK
Server: asmttpd/0.3
Accept-Ranges: bytes
Content-Length: 9223372036854775807                <- ERROR
Content-Type: application/octet-stream
```

index.html:

```
hello
```

**Comment by nemasu** [comment]
Hello, there is no HEAD support, I suppose it should respond as such, but it's currently not implemented to do so.

**Comment by triforce** [comment]
This needs to be reopened as an invalid length is being returned from a HEAD request.

**Comment by nemasu** [comment]
I think it should be returning a 405 error, or the feature be implemented.

**Comment by triforce** [comment]
It should return a 200 response but without a message body, but obviously the content length needs to be calculated correctly.
