### ISSUE TITLE
FASM version

### ISSUE THREAD

**Issue by triforce** [nemasu/asmttpd#18]
How would you feel about a FASM (flat assembler) version of asmttpd? I would be interested in creating and maintaining one.

**Comment by nemasu** [comment]
Sure, I have no objections.

**Comment by triforce** [comment]
Would you like it as a branch of this repository?

**Comment by nemasu** [comment]
Hmm, I'm not too familiar with FASM, will the code be substantially different? Or is it minor changes?
If it's completely different, then a branch probably wouldn't make sense.

**Comment by triforce** [comment]
There are minor syntax changes in each file (from my first pass over it). I will fork your repo and create a branch that I will maintain if that is OK?

**Comment by nemasu** [comment]
Ah okay, yeah sounds good.
