### ISSUE TITLE
Use GNU assembler instead of yasm

### ISSUE THREAD

**Issue by DmitryHetman** [nemasu/asmttpd#27]
In order to achieve better portability it's better to use 'as' instead, it can be installed on ARM64, POWER9, MIPS, most OS supported.
Most GNU/Linux distros have gcc by default, but not yasm.

**Comment by nemasu** [comment]
Does 'as' assemble it with no source changes?

**Comment by triforce** [comment]
> Does 'as' assemble it with no source changes?

Nope it is a different syntax. There is a **.intel_syntax noprefix** option but the code will probably still require changes.

It would be nice if it worked on ARM due to it being the main player in the IoT's.
