### ISSUE TITLE
[Question] Does this run on Raspberry Pi?

### ISSUE THREAD

**Issue by RyanNerd** [nemasu/asmttpd#29]
I'm thinking about tinkering with the Raspberry and this `httpd` with such a small footprint seems to be a perfect thing to experiment with in this environment. Just wondering if anyone has done anything on the Pi and any advice?

**Comment by haneefmubarak** [comment]
`asmttpd` is written in amd64 (x86_64) assembly, meaning it would only run on mainly Intel or AMD machines. Unfortunately, as the RasPi uses the ARM architecture (which makes more sense for low-cost and power efficient devices), this software would not be compatible and would thus not be able to run on a RasPi.

:(
