### ISSUE TITLE
Program cannot be restarted right away after exiting if clients have connected.

### ISSUE THREAD

**Issue by nemasu** [nemasu/asmttpd#31]
Listening socket isn't closed when program exists.

**Comment by triforce** [comment]
Do we need to use a **shutdown** before the sys_close call?

**Comment by nemasu** [comment]
Ah my bad, I think instead of using shutdown, we just need to add the flag SO_REUSEADDR to the bind port.

**Comment by triforce** [comment]
So we will need another syscall to SYS_SETSOCKOPT with rdx = SO_REUSEADDR after sys_create_tcp_socket.

The pointer to 1 might be an issue as the stack isn't setup the same as it is for the cork syscalls so may need to make use of some r registers to save the rbp/rsp?

**Comment by nemasu** [comment]
I've changed it to use bss data instead of stack, and it's calling the correct functions successfully, but I still get the bind error when I close it after a client connects.

**Comment by nemasu** [comment]
Ah, I figured it out, need to call REUSEADDR before bind, not after. :)
