### ISSUE TITLE
can performance kill nginx?

### ISSUE THREAD

**Issue by memorycancel** [nemasu/asmttpd#42]
as the title

**Comment by nemasu** [comment]
Probably not at the moment, I think it needs asynchronous i/o to do that.

**Comment by memorycancel** [comment]
Yeah nginx using asynchronous i/o to improve lots of performance. but I think multi-process or multi-thread can also improve the performance maybe. and coding less and easier.

**Comment by CodeSwimBikeRun** [comment]
Is it not multi threaded atm?

**Comment by nemasu** [comment]
It is multi-threaded still.
