### ISSUE TITLE
Please add Documentation

### ISSUE THREAD

**Issue by CSDUMMI** [nemasu/asmttpd#44]
The whole Project has no single Documentation File besides README and Comments in the Source Code. I want to understand this project, but without Documentation, this task gets even harder.

**Comment by triforce** [comment]
What documentation do you think is needed?

**Comment by CSDUMMI** [comment]
I need a description of the important data, functions, etc.,
if I want to understand the Codebase.
The Documentation should answer these questions:
- How is this project constructed?
- How can you call a function, how can you pass arguments to it?
- What does a function do?
And if you don't give any documentation to a assembly language
project, you give us, who want to understand your project, almost nothing
more than we would get if we reverse engineer a similar project.

**Comment by nemasu** [comment]
Most if not all functions have a comment associated with it that specifies arguments and return parameter and are named to be descriptive as to their function. I don't really have time to make HTML documentation at the moment. If you have any questions though feel free to ask.
