### ISSUE TITLE
Support HTTP/2

### ISSUE THREAD

**Issue by sfxworks** [nemasu/asmttpd#48]
I have a kubernetes ingress controller in front of this. It seems it only works if I disable http/2. Can this be implemented?

**Comment by nemasu** [comment]
It wont fall back to HTTP/1?
I wasn't planning on implementing HTTP/2, or at least, not before things like directory listing.

**Comment by sfxworks** [comment]
Oh

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#proxy-http-version

Disregard. Must have been another issue. I will find out.
