### ISSUE TITLE
was this project abandoned ?

### ISSUE THREAD

**Issue by Slender1808** [nemasu/asmttpd#51]
was this project abandoned ?

**Comment by nemasu** [comment]
Nope. I'm hoping to allocate some time later this year to look at it

**Comment by Slender1808** [comment]
I think the idea of ​​this project is very good, I would like to contribute to the project

**Comment by triforce** [comment]
> I think the idea of ​​this project is very good, I would like to contribute to the project

There are plenty of outstanding issues to contribute to ;)

**Comment by dulatello08** [comment]
> I think the idea of ​​this project is very good, I would like to contribute to the project

You are welcome
